### ISSUE TITLE
MicrogliaMorphologyR Package Trouble

### ISSUE THREAD

**Issue by alanagar** [ciernialab/MicrogliaMorphology#1]
Hello, 

I wanted to reach out about some difficulty I've been having with installing and accessing the _MicrogliaMorphologyR_ package in RStudio. When I attempt to install the package, a warning message appears (see attached). I've tried to troubleshoot by reinstalling the most recent versions of RStudio and R as well as several other CRAN suggestions -- but unfortunately the warning persists. There didn't appear to be any issues with using _devtools_ to access the github, so it seems like I'm struggling with the _MicrogliaMorphologyR_ package itself. I would be grateful for any suggestions or help you may have. Thank you!

<img width="604" alt="Screen Shot 2024-06-24 at 10 27 38 AM" src="https://github.com/ciernialab/MicrogliaMorphology/assets/173827213/12d3a4ab-8286-4ae9-ad0f-78dd8e8cd81c">

**Comment by jenn-kim** [comment]
Hello! The R package is not registered on CRAN, so you will have to use the following code to install it:
`devtools::install_github('ciernialab/MicrogliaMorphologyR')`
